name: CI & Release

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run test:ci
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: junit.xml

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run build:prod
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: compiled
          path: compiled/

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run build:prod
      - name: Get tag name
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: Directus Extension Installer v${{ env.TAG }}
          body_path: RELEASE.md
          files: |
            compiled/directus-extension-installer-alpine
            compiled/directus-extension-installer-macos
            compiled/directus-extension-installer-win.exe
